# Generated by Django 4.0.5 on 2022-06-15 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0002_remove_product_description_product_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='scores',
        ),
    ]
